#!/bin/sh
# Copyright (C) 2018 Toradex
# Licensed on MIT

#
# Starts psplash early in initramfs
# Three kernel command-line parameters are supported:
# - nosplash (disables psplash support)
# - splash.angle=[0,90,180,270] (rotates splash)
# - splash.novtswitch (does not do any console switch)
#

psplash_enabled() {
	if [ ! -e /usr/bin/psplash ]; then
		debug "/usr/bin/psplash doesn't exist"
		return 1
	fi

	return 0
}

psplash_hook_handler() {
	status=$1
	module=$2

	if [ "$module" = "finish" ]; then
		psplash-write "PROGRESS 15"
	fi
}

psplash_run() {
	if [ "$bootparam_nosplash" = "true" ]; then
		return 0
	fi
	if [ -n "$bootparam_splash_angle" ]; then
		PSPLASH_ARGS="--angle $bootparam_splash_angle"
	fi
	if [ "$bootparam_splash_novtswitch" = "true" ]; then
		PSPLASH_ARGS="${PSPLASH_ARGS} -n"
	fi
	psplash $PSPLASH_ARGS &
	add_module_pre_hook "psplash_hook_handler"
}
