export sites="github.com/AlecAivazis/survey/v2:github.com/AlecAivazis/survey/v2 \
           github.com/buger/goterm:github.com/buger/goterm \
           github.com/compose-spec/compose-go:github.com/compose-spec/compose-go \
           github.com/containerd/console:github.com/containerd/console \
           github.com/containerd/containerd:github.com/containerd/containerd \
           github.com/cucumber/godog:github.com/cucumber/godog \
           github.com/distribution/distribution/v3:github.com/distribution/distribution/v3 \
           github.com/docker/buildx:github.com/docker/buildx \
           github.com/docker/cli:github.com/docker/cli \
           github.com/docker/cli-docs-tool:github.com/docker/cli-docs-tool \
           github.com/docker/docker:github.com/docker/docker \
           github.com/docker/go-connections:github.com/docker/go-connections \
           github.com/docker/go-units:github.com/docker/go-units \
           github.com/fsnotify/fsnotify:github.com/fsnotify/fsnotify \
           github.com/golang/mock:github.com/golang/mock \
           github.com/hashicorp/go-multierror:github.com/hashicorp/go-multierror \
           github.com/hashicorp/go-version:github.com/hashicorp/go-version \
           github.com/mattn/go-shellwords:github.com/mattn/go-shellwords \
           github.com/mitchellh/mapstructure:github.com/mitchellh/mapstructure \
           github.com/moby/buildkit:github.com/moby/buildkit \
           github.com/moby/term:github.com/moby/term \
           github.com/morikuni/aec:github.com/morikuni/aec \
           github.com/opencontainers/go-digest:github.com/opencontainers/go-digest \
           github.com/opencontainers/image-spec:github.com/opencontainers/image-spec \
           github.com/pkg/errors:github.com/pkg/errors \
           github.com/sirupsen/logrus:github.com/sirupsen/logrus \
           github.com/spf13/cobra:github.com/spf13/cobra \
           github.com/spf13/pflag:github.com/spf13/pflag \
           github.com/stretchr/testify:github.com/stretchr/testify \
           github.com/theupdateframework/notary:github.com/theupdateframework/notary \
           go.opentelemetry.io/otel:go.opentelemetry.io/otel \
           go.opentelemetry.io/otel/exporters/otlp/internal/retry:github.com/open-telemetry/opentelemetry-go/exporters/otlp/internal/retry//exporters/otlp/internal/retry:force \
           go.opentelemetry.io/otel/exporters/otlp/otlptrace:github.com/open-telemetry/opentelemetry-go/exporters/otlp/internal/retry//exporters/otlp/otlptrace:force \
           go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc:github.com/open-telemetry/opentelemetry-go/exporters/otlp/internal/retry//exporters/otlp/otlptrace/otlptracegrpc:force \
           go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp:github.com/open-telemetry/opentelemetry-go/exporters/otlp/internal/retry//exporters/otlp/otlptrace/otlptracehttp:force \
           go.opentelemetry.io/otel/internal/metric:github.com/open-telemetry/opentelemetry-go/internal/metric//internal/metric:force \
           go.opentelemetry.io/otel/metric:github.com/open-telemetry/opentelemetry-go/internal/metric//metric:force \
           go.opentelemetry.io/otel/sdk:github.com/open-telemetry/opentelemetry-go/exporters/otlp/internal/retry//sdk:force \
           go.opentelemetry.io/otel/trace:go.opentelemetry.io/otel//trace:force \
           golang.org/x/sync:golang.org/x/sync \
           gopkg.in/yaml.v2:gopkg.in/yaml.v2 \
           gotest.tools/v3:github.com/gotestyourself/gotest.tools \
           k8s.io/client-go:k8s.io/client-go \
           github.com/Azure/go-ansiterm:github.com/Azure/go-ansiterm \
           github.com/Microsoft/go-winio:github.com/Microsoft/go-winio \
           github.com/beorn7/perks:github.com/beorn7/perks \
           github.com/bugsnag/bugsnag-go:github.com/bugsnag/bugsnag-go \
           github.com/cenkalti/backoff/v4:github.com/cenkalti/backoff/v4 \
           github.com/cespare/xxhash/v2:github.com/cespare/xxhash/v2 \
           github.com/cloudflare/cfssl:github.com/cloudflare/cfssl \
           github.com/containerd/continuity:github.com/containerd/continuity \
           github.com/containerd/ttrpc:github.com/containerd/ttrpc \
           github.com/containerd/typeurl:github.com/containerd/typeurl \
           github.com/cucumber/gherkin-go/v19:github.com/cucumber/gherkin-go/v19 \
           github.com/cucumber/messages-go/v16:github.com/cucumber/messages-go/v16 \
           github.com/davecgh/go-spew:github.com/davecgh/go-spew \
           github.com/docker/distribution:github.com/docker/distribution \
           github.com/docker/docker-credential-helpers:github.com/docker/docker-credential-helpers \
           github.com/docker/go:github.com/docker/go \
           github.com/docker/go-metrics:github.com/docker/go-metrics \
           github.com/felixge/httpsnoop:github.com/felixge/httpsnoop \
           github.com/fvbommel/sortorder:github.com/fvbommel/sortorder \
           github.com/go-logr/logr:github.com/go-logr/logr \
           github.com/go-logr/stdr:github.com/go-logr/stdr \
           github.com/gofrs/flock:github.com/gofrs/flock \
           github.com/gofrs/uuid:github.com/gofrs/uuid \
           github.com/gogo/googleapis:github.com/gogo/googleapis \
           github.com/gogo/protobuf:github.com/gogo/protobuf \
           github.com/golang/protobuf:github.com/golang/protobuf \
           github.com/google/go-cmp:github.com/google/go-cmp \
           github.com/google/gofuzz:github.com/google/gofuzz \
           github.com/google/shlex:github.com/google/shlex \
           github.com/googleapis/gnostic:github.com/googleapis/gnostic \
           github.com/gorilla/mux:github.com/gorilla/mux \
           github.com/grpc-ecosystem/go-grpc-middleware:github.com/grpc-ecosystem/go-grpc-middleware \
           github.com/grpc-ecosystem/grpc-gateway:github.com/grpc-ecosystem/grpc-gateway \
           github.com/hashicorp/errwrap:github.com/hashicorp/errwrap \
           github.com/hashicorp/go-immutable-radix:github.com/hashicorp/go-immutable-radix \
           github.com/hashicorp/go-memdb:github.com/hashicorp/go-memdb \
           github.com/hashicorp/golang-lru:github.com/hashicorp/golang-lru \
           github.com/imdario/mergo:github.com/imdario/mergo \
           github.com/inconshreveable/mousetrap:github.com/inconshreveable/mousetrap \
           github.com/jinzhu/gorm:github.com/jinzhu/gorm \
           github.com/jonboulle/clockwork:github.com/jonboulle/clockwork \
           github.com/json-iterator/go:github.com/json-iterator/go \
           github.com/kballard/go-shellquote:github.com/kballard/go-shellquote \
           github.com/klauspost/compress:github.com/klauspost/compress \
           github.com/mattn/go-colorable:github.com/mattn/go-colorable \
           github.com/mattn/go-isatty:github.com/mattn/go-isatty \
           github.com/mattn/go-runewidth:github.com/mattn/go-runewidth \
           github.com/matttproud/golang_protobuf_extensions:github.com/matttproud/golang_protobuf_extensions \
           github.com/mgutz/ansi:github.com/mgutz/ansi \
           github.com/miekg/pkcs11:github.com/miekg/pkcs11 \
           github.com/moby/locker:github.com/moby/locker \
           github.com/moby/patternmatcher:github.com/moby/patternmatcher \
           github.com/moby/spdystream:github.com/moby/spdystream \
           github.com/moby/sys/sequential:github.com/moby/sys/sequential//sequential \
           github.com/moby/sys/signal:github.com/moby/sys/signal//signal \
           github.com/moby/sys/symlink:github.com/moby/sys/symlink//symlink \
           github.com/modern-go/concurrent:github.com/modern-go/concurrent \
           github.com/modern-go/reflect2:github.com/modern-go/reflect2 \
           github.com/opencontainers/runc:github.com/opencontainers/runc \
           github.com/pelletier/go-toml:github.com/pelletier/go-toml \
           github.com/pmezard/go-difflib:github.com/pmezard/go-difflib \
           github.com/prometheus/client_golang:github.com/prometheus/client_golang \
           github.com/prometheus/client_model:github.com/prometheus/client_model \
           github.com/prometheus/common:github.com/prometheus/common \
           github.com/prometheus/procfs:github.com/prometheus/procfs \
           github.com/rivo/uniseg:github.com/rivo/uniseg \
           github.com/serialx/hashring:github.com/serialx/hashring \
           github.com/spf13/viper:github.com/spf13/viper \
           github.com/tonistiigi/fsutil:github.com/tonistiigi/fsutil \
           github.com/tonistiigi/units:github.com/tonistiigi/units \
           github.com/tonistiigi/vt100:github.com/tonistiigi/vt100 \
           github.com/xeipuuv/gojsonpointer:github.com/xeipuuv/gojsonpointer \
           github.com/xeipuuv/gojsonreference:github.com/xeipuuv/gojsonreference \
           github.com/xeipuuv/gojsonschema:github.com/xeipuuv/gojsonschema \
           github.com/zmap/zcrypto:github.com/zmap/zcrypto \
           github.com/zmap/zlint:github.com/zmap/zlint \
           go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc:github.com/open-telemetry/opentelemetry-go-contrib/instrumentation/google.golang.org/grpc/otelgrpc//instrumentation/google.golang.org/grpc/otelgrpc \
           go.opentelemetry.io/contrib/instrumentation/net/http/httptrace/otelhttptrace:github.com/open-telemetry/opentelemetry-go-contrib/instrumentation/google.golang.org/grpc/otelgrpc//instrumentation/net/http/httptrace/otelhttptrace \
           go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp:github.com/open-telemetry/opentelemetry-go-contrib/instrumentation/google.golang.org/grpc/otelgrpc//instrumentation/net/http/otelhttp \
           go.opentelemetry.io/proto/otlp:github.com/open-telemetry/opentelemetry-proto-go/otlp//otlp \
           golang.org/x/crypto:golang.org/x/crypto \
           golang.org/x/net:golang.org/x/net \
           golang.org/x/oauth2:golang.org/x/oauth2 \
           golang.org/x/sys:golang.org/x/sys \
           golang.org/x/term:golang.org/x/term \
           golang.org/x/text:golang.org/x/text \
           golang.org/x/time:golang.org/x/time \
           google.golang.org/appengine:github.com/golang/appengine \
           google.golang.org/genproto:github.com/googleapis/go-genproto \
           google.golang.org/grpc:github.com/grpc/grpc-go \
           google.golang.org/protobuf:github.com/protocolbuffers/protobuf-go \
           gopkg.in/inf.v0:gopkg.in/inf.v0 \
           gopkg.in/yaml.v3:gopkg.in/yaml.v3 \
           k8s.io/klog/v2:k8s.io/klog/v2 \
           k8s.io/utils:k8s.io/utils \
           sigs.k8s.io/structured-merge-diff/v4:sigs.k8s.io/structured-merge-diff/v4 \
           sigs.k8s.io/yaml:sigs.k8s.io/yaml \
           github.com/cucumber/godog:github.com/cucumber/godog \
           k8s.io/api:k8s.io/api \
           k8s.io/apimachinery:k8s.io/apimachinery"


do_compile:prepend() {
    cd ${S}/src/import
    for s in $sites; do
        site_dest=$(echo $s | cut -d: -f1)
        site_source=$(echo $s | cut -d: -f2)
        force_flag=$(echo $s | cut -d: -f3)
        mkdir -p vendor.copy/$site_dest
        if [ -n "$force_flag" ]; then
	    echo "[INFO] $site_dest: force copying .go files"
	    rm -rf vendor.copy/$site_dest
	    rsync -a --exclude='vendor/' --exclude='.git/' vendor.fetch/$site_source/ vendor.copy/$site_dest
        else
            [ -n "$(ls -A vendor.copy/$site_dest/*.go 2> /dev/null)" ] && { echo "[INFO] vendor.fetch/$site_source -> $site_dest: go copy skipped (files present)" ; true ; } || { echo "[INFO] $site_dest: copying .go files" ; rsync -a --exclude='vendor/' --exclude='.git/' vendor.fetch/$site_source/ vendor.copy/$site_dest ; }
        fi
    done
}
