sites="github.com/AlecAivazis/survey/v2:github.com/AlecAivazis/survey/v2 \
           github.com/buger/goterm:github.com/buger/goterm \
           github.com/cnabio/cnab-to-oci:github.com/cnabio/cnab-to-oci \
           github.com/compose-spec/compose-go:github.com/compose-spec/compose-go \
           github.com/containerd/console:github.com/containerd/console \
           github.com/containerd/containerd:github.com/containerd/containerd \
           github.com/distribution/distribution/v3:github.com/distribution/distribution/v3 \
           github.com/docker/cli:github.com/docker/cli \
           github.com/docker/cli-docs-tool:github.com/docker/cli-docs-tool \
           github.com/docker/docker:github.com/docker/docker \
           github.com/docker/docker:github.com/docker/docker83b51522df43866e39f7c757a6ab84ef4050eeb3 \
           github.com/docker/go-connections:github.com/docker/go-connections \
           github.com/docker/go-units:github.com/docker/go-units \
           github.com/golang/mock:github.com/golang/mock \
           github.com/hashicorp/go-multierror:github.com/hashicorp/go-multierror \
           github.com/hashicorp/go-version:github.com/hashicorp/go-version \
           github.com/mattn/go-isatty:github.com/mattn/go-isatty \
           github.com/mattn/go-shellwords:github.com/mattn/go-shellwords \
           github.com/moby/buildkit:github.com/moby/buildkit \
           github.com/moby/term:github.com/moby/term \
           github.com/morikuni/aec:github.com/morikuni/aec \
           github.com/opencontainers/go-digest:github.com/opencontainers/go-digest \
           github.com/opencontainers/image-spec:github.com/opencontainers/image-spec \
           github.com/pkg/errors:github.com/pkg/errors \
           github.com/sirupsen/logrus:github.com/sirupsen/logrus \
           github.com/spf13/cobra:github.com/spf13/cobra \
           github.com/spf13/pflag:github.com/spf13/pflag \
           github.com/stretchr/testify:github.com/stretchr/testify \
           github.com/theupdateframework/notary:github.com/theupdateframework/notary \
           golang.org/x/sync:golang.org/x/sync \
           gopkg.in/yaml.v2:gopkg.in/yaml.v2 \
           gotest.tools:github.com/gotestyourself/gotest.tools \
           gotest.tools/v3:github.com/gotestyourself/gotest.toolsf086d2783c5b3a2a21b482ec19c1c310e68f4d18 \
           github.com/Azure/go-ansiterm:github.com/Azure/go-ansiterm \
           github.com/Masterminds/semver:github.com/Masterminds/semver \
           github.com/Microsoft/go-winio:github.com/Microsoft/go-winio \
           github.com/beorn7/perks:github.com/beorn7/perks \
           github.com/cespare/xxhash/v2:github.com/cespare/xxhash/v2 \
           github.com/cnabio/cnab-go:github.com/cnabio/cnab-go \
           github.com/containerd/continuity:github.com/containerd/continuity \
           github.com/containerd/ttrpc:github.com/containerd/ttrpc \
           github.com/containerd/typeurl:github.com/containerd/typeurl \
           github.com/davecgh/go-spew:github.com/davecgh/go-spew \
           github.com/docker/distribution:github.com/docker/distribution \
           github.com/docker/docker-credential-helpers:github.com/docker/docker-credential-helpers \
           github.com/docker/go:github.com/docker/go \
           github.com/docker/go-metrics:github.com/docker/go-metrics \
           github.com/felixge/httpsnoop:github.com/felixge/httpsnoop \
           github.com/fvbommel/sortorder:github.com/fvbommel/sortorder \
           github.com/go-logr/logr:github.com/go-logr/logr \
           github.com/go-logr/stdr:github.com/go-logr/stdr \
           github.com/gofrs/flock:github.com/gofrs/flock \
           github.com/gogo/googleapis:github.com/gogo/googleapis \
           github.com/gogo/protobuf:github.com/gogo/protobuf \
           github.com/golang/protobuf:github.com/golang/protobuf \
           github.com/google/go-cmp:github.com/google/go-cmp \
           github.com/google/gofuzz:github.com/google/gofuzz \
           github.com/google/shlex:github.com/google/shlex \
           github.com/gorilla/mux:github.com/gorilla/mux \
           github.com/grpc-ecosystem/go-grpc-middleware:github.com/grpc-ecosystem/go-grpc-middleware \
           github.com/grpc-ecosystem/grpc-gateway:github.com/grpc-ecosystem/grpc-gateway \
           github.com/hashicorp/errwrap:github.com/hashicorp/errwrap \
           github.com/imdario/mergo:github.com/imdario/mergo \
           github.com/inconshreveable/mousetrap:github.com/inconshreveable/mousetrap \
           github.com/json-iterator/go:github.com/json-iterator/go \
           github.com/kballard/go-shellquote:github.com/kballard/go-shellquote \
           github.com/klauspost/compress:github.com/klauspost/compress \
           github.com/mattn/go-colorable:github.com/mattn/go-colorable \
           github.com/matttproud/golang_protobuf_extensions:github.com/matttproud/golang_protobuf_extensions \
           github.com/mgutz/ansi:github.com/mgutz/ansi \
           github.com/miekg/pkcs11:github.com/miekg/pkcs11 \
           github.com/mitchellh/mapstructure:github.com/mitchellh/mapstructure \
           github.com/moby/locker:github.com/moby/locker \
           github.com/moby/sys/signal:github.com/moby/sys/signal//signal \
           github.com/moby/sys/symlink:github.com/moby/sys/symlink//symlink \
           github.com/modern-go/concurrent:github.com/modern-go/concurrent \
           github.com/modern-go/reflect2:github.com/modern-go/reflect2 \
           github.com/opencontainers/runc:github.com/opencontainers/runc \
           github.com/pelletier/go-toml:github.com/pelletier/go-toml \
           github.com/pmezard/go-difflib:github.com/pmezard/go-difflib \
           github.com/prometheus/client_golang:github.com/prometheus/client_golang \
           github.com/prometheus/client_model:github.com/prometheus/client_model \
           github.com/prometheus/common:github.com/prometheus/common \
           github.com/prometheus/procfs:github.com/prometheus/procfs \
           github.com/qri-io/jsonpointer:github.com/qri-io/jsonpointer \
           github.com/qri-io/jsonschema:github.com/qri-io/jsonschema \
           github.com/tonistiigi/fsutil:github.com/tonistiigi/fsutil \
           github.com/tonistiigi/units:github.com/tonistiigi/units \
           github.com/tonistiigi/vt100:github.com/tonistiigi/vt100 \
           github.com/xeipuuv/gojsonpointer:github.com/xeipuuv/gojsonpointer \
           github.com/xeipuuv/gojsonreference:github.com/xeipuuv/gojsonreference \
           github.com/xeipuuv/gojsonschema:github.com/xeipuuv/gojsonschema \
           go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc:github.com/open-telemetry/opentelemetry-go-contrib/instrumentation/google.golang.org/grpc/otelgrpc//instrumentation/google.golang.org/grpc/otelgrpc \
           go.opentelemetry.io/contrib/instrumentation/net/http/httptrace/otelhttptrace:github.com/open-telemetry/opentelemetry-go-contrib/instrumentation/google.golang.org/grpc/otelgrpc//instrumentation/net/http/httptrace/otelhttptrace \
           go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp:github.com/open-telemetry/opentelemetry-go-contrib/instrumentation/google.golang.org/grpc/otelgrpc//instrumentation/net/http/otelhttp \
           go.opentelemetry.io/otel:go.opentelemetry.io/otel \
           go.opentelemetry.io/otel/exporters/otlp/otlptrace:github.com/open-telemetry/opentelemetry-go/exporters/otlp/otlptrace//exporters/otlp/otlptrace:force \
           go.opentelemetry.io/otel/internal/metric:github.com/open-telemetry/opentelemetry-go/internal/metric//internal/metric:force \
           go.opentelemetry.io/otel/metric:github.com/open-telemetry/opentelemetry-go/metric//metric:force \
           go.opentelemetry.io/otel/sdk:github.com/open-telemetry/opentelemetry-go/exporters/otlp/otlptrace//sdk:force \
           go.opentelemetry.io/otel/trace:go.opentelemetry.io/otel//trace:force \
           go.opentelemetry.io/otel/exporters/otlp/internal/retry:github.com/open-telemetry/opentelemetry-go/exporters/otlp/otlptrace//exporters/otlp/internal/retry:force \
           go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc:github.com/open-telemetry/opentelemetry-go/exporters/otlp/otlptrace//exporters/otlp/otlptrace/otlptracegrpc:force \
           go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp:github.com/open-telemetry/opentelemetry-go/exporters/otlp/otlptrace//exporters/otlp/otlptrace/otlptracehttp:force \
           go.opentelemetry.io/proto/otlp:github.com/open-telemetry/opentelemetry-proto-go/otlp//otlp:force \
           golang.org/x/crypto:golang.org/x/crypto \
           golang.org/x/net:golang.org/x/net \
           golang.org/x/oauth2:golang.org/x/oauth2 \
           golang.org/x/sys:golang.org/x/sys \
           golang.org/x/term:golang.org/x/term \
           golang.org/x/text:golang.org/x/text \
           golang.org/x/time:golang.org/x/time \
           google.golang.org/appengine:github.com/golang/appengine \
           google.golang.org/genproto:github.com/googleapis/go-genproto \
           google.golang.org/grpc:github.com/grpc/grpc-go \
           google.golang.org/protobuf:github.com/protocolbuffers/protobuf-go \
           gopkg.in/inf.v0:gopkg.in/inf.v0 \
           gopkg.in/yaml.v3:gopkg.in/yaml.v3 \
           k8s.io/klog/v2:k8s.io/klog/v2 \
           k8s.io/utils:k8s.io/utils \
           sigs.k8s.io/structured-merge-diff/v4:sigs.k8s.io/structured-merge-diff/v4 \
           sigs.k8s.io/yaml:sigs.k8s.io/yaml \
           github.com/cenkalti/backoff/v4:github.com/cenkalti/backoff/v4 \
           github.com/cyberphone/json-canonicalization:github.com/cyberphone/json-canonicalization \
           github.com/googleapis/gnostic:github.com/googleapis/gnostic \
           github.com/moby/spdystream:github.com/moby/spdystream \
           github.com/serialx/hashring:github.com/serialx/hashring \
           github.com/zmap/zcrypto:github.com/zmap/zcrypto \
           github.com/zmap/zlint:github.com/zmap/zlint \
           k8s.io/api:k8s.io/api \
           k8s.io/apimachinery:k8s.io/apimachinery \
           k8s.io/client-go:k8s.io/client-go \
           github.com/docker/buildx:github.com/docker/buildx \
           github.com/moby/sys/mount:github.com/moby/sys/mount//mount \
           github.com/moby/sys/mountinfo:github.com/moby/sys/mountinfo//mountinfo \
           github.com/moby/sys/signal:github.com/moby/sys/mountinfo//signal \
           github.com/moby/sys/symlink:github.com/moby/sys/symlink//symlink \
"

do_compile:prepend() {
        cd ${S}/src/import
	# this moves all the fetches into the proper vendor structure
	# expected for build
	for s in ${sites}; do
            site_dest=$(echo $s | cut -d: -f1)
            site_source=$(echo $s | cut -d: -f2)
	    force_flag=$(echo $s | cut -d: -f3)
            mkdir -p vendor.copy/$site_dest
	    if [ -n "$force_flag" ]; then
		echo "[INFO] $site_dest: force copying .go files"
		rm -rf vendor.copy/$site_dest
		rsync -a --exclude='vendor/' --exclude='.git/' vendor.fetch/$site_source/ vendor.copy/$site_dest
	    else
		[ -n "$(ls -A vendor.copy/$site_dest/*.go 2> /dev/null)" ] && { echo "[INFO] vendor.fetch/$site_source -> $site_dest: go copy skipped (files present)" ; true ; } || { echo "[INFO] $site_dest: copying .go files" ; rsync -a --exclude='vendor/' --exclude='.git/' vendor.fetch/$site_source/ vendor.copy/$site_dest ; }
	    fi
	done
}