# 	github.com/AlecAivazis/survey/v2 v2.3.6
# [1] git ls-remote https://github.com/AlecAivazis/survey 55474c34196ae637a7633f511e63509d19188b59 
SRCREV_v2="55474c34196ae637a7633f511e63509d19188b59"
SRC_URI += "git://github.com/AlecAivazis/survey;name=v2;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/AlecAivazis/survey/v2"

# 	github.com/buger/goterm v1.0.4
# [1] git ls-remote https://github.com/buger/goterm a73545aae7d693f786ce4cc687460efca4845f31 
SRCREV_goterm="a73545aae7d693f786ce4cc687460efca4845f31"
SRC_URI += "git://github.com/buger/goterm;name=goterm;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/buger/goterm"

# 	github.com/cnabio/cnab-to-oci v0.3.7
# [1] git ls-remote https://github.com/cnabio/cnab-to-oci fadbd1723115c53acb8007c36a855af1bac57d34 
SRCREV_cnab-to-oci="fadbd1723115c53acb8007c36a855af1bac57d34"
SRC_URI += "git://github.com/cnabio/cnab-to-oci;name=cnab-to-oci;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/cnabio/cnab-to-oci"

# 	github.com/compose-spec/compose-go v1.6.0
# [1] git ls-remote https://github.com/compose-spec/compose-go 08a21dff3db4be06ac783b3eaea2cd9de9cc0f81 
SRCREV_compose-go="08a21dff3db4be06ac783b3eaea2cd9de9cc0f81"
SRC_URI += "git://github.com/compose-spec/compose-go;name=compose-go;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/compose-spec/compose-go"

# 	github.com/containerd/console v1.0.3
# [1] git ls-remote https://github.com/containerd/console b5cb846c9186d67bcae3ce3c324e47cd317d9527 
SRCREV_console="b5cb846c9186d67bcae3ce3c324e47cd317d9527"
SRC_URI += "git://github.com/containerd/console;name=console;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/containerd/console"

# 	github.com/containerd/containerd v1.6.8
# [1] git ls-remote https://github.com/containerd/containerd 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6 
SRCREV_containerd="9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6"
SRC_URI += "git://github.com/containerd/containerd;name=containerd;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/containerd/containerd"

# 	github.com/distribution/distribution/v3 v3.0.0-20220907155224-78b9c98c5c31
# [1] git ls-remote https://github.com/distribution/distribution 78b9c98c5c31c30d74f9acb7d96f98552f2cf78f 
SRCREV_v3="78b9c98c5c31c30d74f9acb7d96f98552f2cf78f"
SRC_URI += "git://github.com/distribution/distribution;name=v3;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/distribution/distribution/v3"

# 	github.com/docker/cli-docs-tool v0.5.0
# [1] git ls-remote https://github.com/docker/cli-docs-tool 77abede22166eaea4af7335096bdcedd043f5b19 
SRCREV_cli-docs-tool="77abede22166eaea4af7335096bdcedd043f5b19"
SRC_URI += "git://github.com/docker/cli-docs-tool;name=cli-docs-tool;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/docker/cli-docs-tool"

# github.com/docker/docker v20.10.3-0.20220309172631-83b51522df43+incompatible
# [1] git ls-remote https://github.com/docker/docker 83b51522df43866e39f7c757a6ab84ef4050eeb3
SRCREV_docker="83b51522df43866e39f7c757a6ab84ef4050eeb3"
SRC_URI += "git://github.com/docker/docker;name=docker;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/docker/docker"

# 	github.com/docker/go-connections v0.4.0
# [1] git ls-remote https://github.com/docker/go-connections 7395e3f8aa162843a74ed6d48e79627d9792ac55 
SRCREV_go-connections="7395e3f8aa162843a74ed6d48e79627d9792ac55"
SRC_URI += "git://github.com/docker/go-connections;name=go-connections;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/docker/go-connections"

# 	github.com/docker/go-units v0.5.0
# [1] git ls-remote https://github.com/docker/go-units e682442797b36348f8e1f98defdbf32bac0b6c6f 
SRCREV_go-units="e682442797b36348f8e1f98defdbf32bac0b6c6f"
SRC_URI += "git://github.com/docker/go-units;name=go-units;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/docker/go-units"

# 	github.com/golang/mock v1.6.0
# [1] git ls-remote https://github.com/golang/mock aba2ff9a6844d5e3289e8472d3217d5b3090f083 
SRCREV_mock="aba2ff9a6844d5e3289e8472d3217d5b3090f083"
SRC_URI += "git://github.com/golang/mock;name=mock;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/golang/mock"

# 	github.com/hashicorp/go-multierror v1.1.1
# [1] git ls-remote https://github.com/hashicorp/go-multierror 9974e9ec57696378079ecc3accd3d6f29401b3a0 
SRCREV_go-multierror="9974e9ec57696378079ecc3accd3d6f29401b3a0"
SRC_URI += "git://github.com/hashicorp/go-multierror;name=go-multierror;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/hashicorp/go-multierror"

# 	github.com/hashicorp/go-version v1.6.0
# [1] git ls-remote https://github.com/hashicorp/go-version 78d058c5618891f74d604bd15356fca690b64d8a 
SRCREV_go-version="78d058c5618891f74d604bd15356fca690b64d8a"
SRC_URI += "git://github.com/hashicorp/go-version;name=go-version;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/hashicorp/go-version"

# 	github.com/mattn/go-isatty v0.0.16
# [1] git ls-remote https://github.com/mattn/go-isatty 13e91bf4058fb93d5629deb7b2e3763ec8f4fdf8 
SRCREV_go-isatty="13e91bf4058fb93d5629deb7b2e3763ec8f4fdf8"
SRC_URI += "git://github.com/mattn/go-isatty;name=go-isatty;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/mattn/go-isatty"

# 	github.com/mattn/go-shellwords v1.0.12
# [1] git ls-remote https://github.com/mattn/go-shellwords 973b9d5391598d4ee601db46fa32f6e186a356ac 
SRCREV_go-shellwords="973b9d5391598d4ee601db46fa32f6e186a356ac"
SRC_URI += "git://github.com/mattn/go-shellwords;name=go-shellwords;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/mattn/go-shellwords"

# 	github.com/moby/buildkit v0.10.4
# [1] git ls-remote https://github.com/moby/buildkit a2ba6869363812a210fcc3ded6926757ab780b5f 
SRCREV_buildkit="a2ba6869363812a210fcc3ded6926757ab780b5f"
SRC_URI += "git://github.com/moby/buildkit;name=buildkit;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/moby/buildkit"

# 	github.com/moby/term v0.0.0-20220808134915-39b0c02b01ae
# [1] git ls-remote https://github.com/moby/term 39b0c02b01ae42267247a54c2bd47c43672d3315 
SRCREV_term="39b0c02b01ae42267247a54c2bd47c43672d3315"
SRC_URI += "git://github.com/moby/term;name=term;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/moby/term"

# 	github.com/morikuni/aec v1.0.0
# [1] git ls-remote https://github.com/morikuni/aec 39771216ff4c63d11f5e604076f9c45e8be1067b 
SRCREV_aec="39771216ff4c63d11f5e604076f9c45e8be1067b"
SRC_URI += "git://github.com/morikuni/aec;name=aec;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/morikuni/aec"

# 	github.com/opencontainers/go-digest v1.0.0
# [1] git ls-remote https://github.com/opencontainers/go-digest ea51bea511f75cfa3ef6098cc253c5c3609b037a 
SRCREV_go-digest="ea51bea511f75cfa3ef6098cc253c5c3609b037a"
SRC_URI += "git://github.com/opencontainers/go-digest;name=go-digest;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/opencontainers/go-digest"

# 	github.com/opencontainers/image-spec v1.0.3-0.20211202183452-c5a74bcca799
# [1] git ls-remote https://github.com/opencontainers/image-spec c5a74bcca799bef045e7fbe74e1b75580fd18d4c 
SRCREV_image-spec="c5a74bcca799bef045e7fbe74e1b75580fd18d4c"
SRC_URI += "git://github.com/opencontainers/image-spec;name=image-spec;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/opencontainers/image-spec"

# 	github.com/pkg/errors v0.9.1
# [1] git ls-remote https://github.com/pkg/errors 614d223910a179a466c1767a985424175c39b465 
SRCREV_errors="614d223910a179a466c1767a985424175c39b465"
SRC_URI += "git://github.com/pkg/errors;name=errors;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/pkg/errors"

# 	github.com/sirupsen/logrus v1.9.0
# [1] git ls-remote https://github.com/sirupsen/logrus f8bf7650dccb756cea26edaf9217aab85500fe07 
SRCREV_logrus="f8bf7650dccb756cea26edaf9217aab85500fe07"
SRC_URI += "git://github.com/sirupsen/logrus;name=logrus;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/sirupsen/logrus"

# 	github.com/spf13/cobra v1.6.0
# [1] git ls-remote https://github.com/spf13/cobra 860791844ed3a2e544a9b9bbbcb14144a948ad20 
SRCREV_cobra="860791844ed3a2e544a9b9bbbcb14144a948ad20"
SRC_URI += "git://github.com/spf13/cobra;name=cobra;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/spf13/cobra"

# 	github.com/spf13/pflag v1.0.5
# [1] git ls-remote https://github.com/spf13/pflag 2e9d26c8c37aae03e3f9d4e90b7116f5accb7cab 
SRCREV_pflag="2e9d26c8c37aae03e3f9d4e90b7116f5accb7cab"
SRC_URI += "git://github.com/spf13/pflag;name=pflag;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/spf13/pflag"

# 	github.com/stretchr/testify v1.8.0
# [1] git ls-remote https://github.com/stretchr/testify 181cea6eab8b2de7071383eca4be32a424db38dd 
SRCREV_testify="181cea6eab8b2de7071383eca4be32a424db38dd"
SRC_URI += "git://github.com/stretchr/testify;name=testify;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/stretchr/testify"

# 	github.com/theupdateframework/notary v0.7.0
# [1] git ls-remote https://github.com/theupdateframework/notary b0b6bfdd4933081e8d5ae026b24e8337311dd598 
SRCREV_notary="b0b6bfdd4933081e8d5ae026b24e8337311dd598"
SRC_URI += "git://github.com/theupdateframework/notary;name=notary;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/theupdateframework/notary"

# 	golang.org/x/sync v0.0.0-20220819030929-7fc1605a5dde
# [1] git ls-remote https://github.com/golang/sync 7fc1605a5dde7535a0fc1770ca44238629ff29ac 
SRCREV_sync="7fc1605a5dde7535a0fc1770ca44238629ff29ac"
SRC_URI += "git://github.com/golang/sync;name=sync;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/sync"

# 	gopkg.in/yaml.v2 v2.4.0
# [1] git ls-remote https://gopkg.in/yaml.v2 7649d4548cb53a614db133b2a8ac1f31859dda8c 
SRCREV_yaml.v2="7649d4548cb53a614db133b2a8ac1f31859dda8c"
SRC_URI += "git://gopkg.in/yaml.v2;name=yaml.v2;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/gopkg.in/yaml.v2"

# 	gotest.tools v2.2.0+incompatible
# [1] git ls-remote https://github.com/gotestyourself/gotest.tools 7c797b5133e5460410dbb22ba779bf35e6975dea 
SRCREV_gotest.tools="7c797b5133e5460410dbb22ba779bf35e6975dea"
SRC_URI += "git://github.com/gotestyourself/gotest.tools;name=gotest.tools;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/gotestyourself/gotest.tools"

# 	gotest.tools/v3 v3.4.0
# [1] git ls-remote https://github.com/gotestyourself/gotest.tools f086d2783c5b3a2a21b482ec19c1c310e68f4d18 
SRCREV_v31="f086d2783c5b3a2a21b482ec19c1c310e68f4d18"
SRC_URI += "git://github.com/gotestyourself/gotest.tools;name=v31;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/gotestyourself/gotest.toolsf086d2783c5b3a2a21b482ec19c1c310e68f4d18"

# 	github.com/Azure/go-ansiterm v0.0.0-20210617225240-d185dfc1b5a1
# [1] git ls-remote https://github.com/Azure/go-ansiterm d185dfc1b5a126116ea5a19e148e29d16b4574c9 
SRCREV_go-ansiterm="d185dfc1b5a126116ea5a19e148e29d16b4574c9"
SRC_URI += "git://github.com/Azure/go-ansiterm;name=go-ansiterm;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/Azure/go-ansiterm"

# 	github.com/Masterminds/semver v1.5.0
# [1] git ls-remote https://github.com/Masterminds/semver 805c489aa98f412e79eb308a37996bf9d8b1c91e 
SRCREV_semver="805c489aa98f412e79eb308a37996bf9d8b1c91e"
SRC_URI += "git://github.com/Masterminds/semver;name=semver;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/Masterminds/semver"

# 	github.com/Microsoft/go-winio v0.5.2
# [1] git ls-remote https://github.com/Microsoft/go-winio dfd7da8f92a382999d77b5d9cfe8cc6bec1894c6 
SRCREV_go-winio="dfd7da8f92a382999d77b5d9cfe8cc6bec1894c6"
SRC_URI += "git://github.com/Microsoft/go-winio;name=go-winio;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/Microsoft/go-winio"

# 	github.com/beorn7/perks v1.0.1
# [1] git ls-remote https://github.com/beorn7/perks 37c8de3658fcb183f997c4e13e8337516ab753e6 
SRCREV_perks="37c8de3658fcb183f997c4e13e8337516ab753e6"
SRC_URI += "git://github.com/beorn7/perks;name=perks;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/beorn7/perks"

# 	github.com/cespare/xxhash/v2 v2.1.2
# [1] git ls-remote https://github.com/cespare/xxhash e7a6b52374f7e2abfb8abb27249d53a1997b09a7 
SRCREV_v21="e7a6b52374f7e2abfb8abb27249d53a1997b09a7"
SRC_URI += "git://github.com/cespare/xxhash;name=v21;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/cespare/xxhash/v2"

# 	github.com/cnabio/cnab-go v0.23.4
# [1] git ls-remote https://github.com/cnabio/cnab-go 91140cbcd7633af4715aa9767609da084e4799e9 
SRCREV_cnab-go="91140cbcd7633af4715aa9767609da084e4799e9"
SRC_URI += "git://github.com/cnabio/cnab-go;name=cnab-go;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/cnabio/cnab-go"

# 	github.com/containerd/continuity v0.2.3-0.20220330195504-d132b287edc8
# [1] git ls-remote https://github.com/containerd/continuity d132b287edc8ffc79dafab5b941f4acf69e060d0 
SRCREV_continuity="d132b287edc8ffc79dafab5b941f4acf69e060d0"
SRC_URI += "git://github.com/containerd/continuity;name=continuity;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/containerd/continuity"

# 	github.com/containerd/ttrpc v1.1.0
# [1] git ls-remote https://github.com/containerd/ttrpc 0247db16a1f98bb76731a12ad72b8d49705b38b3 
SRCREV_ttrpc="0247db16a1f98bb76731a12ad72b8d49705b38b3"
SRC_URI += "git://github.com/containerd/ttrpc;name=ttrpc;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/containerd/ttrpc"

# 	github.com/containerd/typeurl v1.0.2
# [1] git ls-remote https://github.com/containerd/typeurl 5e43fb8b75ed2f2305fc04e6918c8d10636771bc 
SRCREV_typeurl="5e43fb8b75ed2f2305fc04e6918c8d10636771bc"
SRC_URI += "git://github.com/containerd/typeurl;name=typeurl;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/containerd/typeurl"

# 	github.com/davecgh/go-spew v1.1.1
# [1] git ls-remote https://github.com/davecgh/go-spew 8991bc29aa16c548c550c7ff78260e27b9ab7c73 
SRCREV_go-spew="8991bc29aa16c548c550c7ff78260e27b9ab7c73"
SRC_URI += "git://github.com/davecgh/go-spew;name=go-spew;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/davecgh/go-spew"

# 	github.com/docker/distribution v2.8.1+incompatible
# [1] git ls-remote https://github.com/docker/distribution b5ca020cfbe998e5af3457fda087444cf5116496 
SRCREV_distribution="b5ca020cfbe998e5af3457fda087444cf5116496"
SRC_URI += "git://github.com/docker/distribution;name=distribution;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/docker/distribution"

# 	github.com/docker/docker-credential-helpers v0.6.4
# [1] git ls-remote https://github.com/docker/docker-credential-helpers fc9290adbcf1594e78910e2f0334090eaee0e1ee 
SRCREV_docker-credential-helpers="fc9290adbcf1594e78910e2f0334090eaee0e1ee"
SRC_URI += "git://github.com/docker/docker-credential-helpers;name=docker-credential-helpers;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/docker/docker-credential-helpers"

# 	github.com/docker/go v1.5.1-1.0.20160303222718-d30aec9fd63c
# [1] git ls-remote https://github.com/docker/go d30aec9fd63c35133f8f79c3412ad91a3b08be06 
SRCREV_go="d30aec9fd63c35133f8f79c3412ad91a3b08be06"
SRC_URI += "git://github.com/docker/go;name=go;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/docker/go"

# 	github.com/docker/go-metrics v0.0.1
# [1] git ls-remote https://github.com/docker/go-metrics b619b3592b65de4f087d9f16863a7e6ff905973c 
SRCREV_go-metrics="b619b3592b65de4f087d9f16863a7e6ff905973c"
SRC_URI += "git://github.com/docker/go-metrics;name=go-metrics;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/docker/go-metrics"

# 	github.com/felixge/httpsnoop v1.0.2
# [1] git ls-remote https://github.com/felixge/httpsnoop 42c30f944879059639bcf7b2ca4aba06f4a83198 
SRCREV_httpsnoop="42c30f944879059639bcf7b2ca4aba06f4a83198"
SRC_URI += "git://github.com/felixge/httpsnoop;name=httpsnoop;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/felixge/httpsnoop"

# 	github.com/fvbommel/sortorder v1.0.2
# [1] git ls-remote https://github.com/fvbommel/sortorder 26fad50c6b32a3064c09ed089865c16f2f3615f6 
SRCREV_sortorder="26fad50c6b32a3064c09ed089865c16f2f3615f6"
SRC_URI += "git://github.com/fvbommel/sortorder;name=sortorder;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/fvbommel/sortorder"

# 	github.com/go-logr/logr v1.2.3
# [1] git ls-remote https://github.com/go-logr/logr 47e013cee9b1f91c987cc70a218639655431b607 
SRCREV_logr="47e013cee9b1f91c987cc70a218639655431b607"
SRC_URI += "git://github.com/go-logr/logr;name=logr;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/go-logr/logr"

# 	github.com/go-logr/stdr v1.2.2
# [1] git ls-remote https://github.com/go-logr/stdr 521af2addfa7c81c8a65d0e85ed34bb6bb6dc262 
SRCREV_stdr="521af2addfa7c81c8a65d0e85ed34bb6bb6dc262"
SRC_URI += "git://github.com/go-logr/stdr;name=stdr;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/go-logr/stdr"

# 	github.com/gofrs/flock v0.8.0
# [1] git ls-remote https://github.com/gofrs/flock 75ec202958fd1654ff47064ba3ebffe14443f391 
SRCREV_flock="75ec202958fd1654ff47064ba3ebffe14443f391"
SRC_URI += "git://github.com/gofrs/flock;name=flock;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/gofrs/flock"

# 	github.com/gogo/googleapis v1.4.1
# [1] git ls-remote https://github.com/gogo/googleapis 1f0e43f50bc0606e385ffae1bc80b5b231dcd042 
SRCREV_googleapis="1f0e43f50bc0606e385ffae1bc80b5b231dcd042"
SRC_URI += "git://github.com/gogo/googleapis;name=googleapis;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/gogo/googleapis"

# 	github.com/gogo/protobuf v1.3.2
# [1] git ls-remote https://github.com/gogo/protobuf b03c65ea87cdc3521ede29f62fe3ce239267c1bc 
SRCREV_protobuf="b03c65ea87cdc3521ede29f62fe3ce239267c1bc"
SRC_URI += "git://github.com/gogo/protobuf;name=protobuf;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/gogo/protobuf"

# 	github.com/golang/protobuf v1.5.2
# [1] git ls-remote https://github.com/golang/protobuf ae97035608a719c7a1c1c41bed0ae0744bdb0c6f 
SRCREV_protobuf1="ae97035608a719c7a1c1c41bed0ae0744bdb0c6f"
SRC_URI += "git://github.com/golang/protobuf;name=protobuf1;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/golang/protobuf"

# 	github.com/google/go-cmp v0.5.8
# [1] git ls-remote https://github.com/google/go-cmp f144a35ed4ac538fae93fa3783175108738f71b9 
SRCREV_go-cmp="f144a35ed4ac538fae93fa3783175108738f71b9"
SRC_URI += "git://github.com/google/go-cmp;name=go-cmp;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/google/go-cmp"

# 	github.com/google/gofuzz v1.2.0
# [1] git ls-remote https://github.com/google/gofuzz 379e164120fbc98885a8f494b5aa41ba94f64c56 
SRCREV_gofuzz="379e164120fbc98885a8f494b5aa41ba94f64c56"
SRC_URI += "git://github.com/google/gofuzz;name=gofuzz;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/google/gofuzz"

# 	github.com/google/shlex v0.0.0-20191202100458-e7afc7fbc510
# [1] git ls-remote https://github.com/google/shlex e7afc7fbc51079733e9468cdfd1efcd7d196cd1d 
SRCREV_shlex="e7afc7fbc51079733e9468cdfd1efcd7d196cd1d"
SRC_URI += "git://github.com/google/shlex;name=shlex;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/google/shlex"

# 	github.com/gorilla/mux v1.8.0
# [1] git ls-remote https://github.com/gorilla/mux 98cb6bf42e086f6af920b965c38cacc07402d51b 
SRCREV_mux="98cb6bf42e086f6af920b965c38cacc07402d51b"
SRC_URI += "git://github.com/gorilla/mux;name=mux;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/gorilla/mux"

# 	github.com/grpc-ecosystem/go-grpc-middleware v1.3.0
# [1] git ls-remote https://github.com/grpc-ecosystem/go-grpc-middleware df0f91b29bbbdfc3a686a7a8edbe2b9de2072fdd 
SRCREV_go-grpc-middleware="df0f91b29bbbdfc3a686a7a8edbe2b9de2072fdd"
SRC_URI += "git://github.com/grpc-ecosystem/go-grpc-middleware;name=go-grpc-middleware;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/grpc-ecosystem/go-grpc-middleware"

# 	github.com/grpc-ecosystem/grpc-gateway v1.16.0
# [1] git ls-remote https://github.com/grpc-ecosystem/grpc-gateway 094a6fe78b3ca888297d090185cdf30f0e42e157 
SRCREV_grpc-gateway="094a6fe78b3ca888297d090185cdf30f0e42e157"
SRC_URI += "git://github.com/grpc-ecosystem/grpc-gateway;name=grpc-gateway;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/grpc-ecosystem/grpc-gateway"

# 	github.com/hashicorp/errwrap v1.1.0
# [1] git ls-remote https://github.com/hashicorp/errwrap 7b00e5db719c64d14dd0caaacbd13e76254d02c0 
SRCREV_errwrap="7b00e5db719c64d14dd0caaacbd13e76254d02c0"
SRC_URI += "git://github.com/hashicorp/errwrap;name=errwrap;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/hashicorp/errwrap"

# 	github.com/imdario/mergo v0.3.13
# [1] git ls-remote https://github.com/imdario/mergo 194978757031c1a5c8ff8e059ae75fc2fc2a04f7 
SRCREV_mergo="194978757031c1a5c8ff8e059ae75fc2fc2a04f7"
SRC_URI += "git://github.com/imdario/mergo;name=mergo;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/imdario/mergo"

# 	github.com/inconshreveable/mousetrap v1.0.1
# [1] git ls-remote https://github.com/inconshreveable/mousetrap 3a66f25f8779fad208598f21472174ef7b35c3ec 
SRCREV_mousetrap="3a66f25f8779fad208598f21472174ef7b35c3ec"
SRC_URI += "git://github.com/inconshreveable/mousetrap;name=mousetrap;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/inconshreveable/mousetrap"

# 	github.com/json-iterator/go v1.1.12
# [1] git ls-remote https://github.com/json-iterator/go 024077e996b048517130b21ea6bf12aa23055d3d 
SRCREV_go1="024077e996b048517130b21ea6bf12aa23055d3d"
SRC_URI += "git://github.com/json-iterator/go;name=go1;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/json-iterator/go"

# 	github.com/kballard/go-shellquote v0.0.0-20180428030007-95032a82bc51
# [1] git ls-remote https://github.com/kballard/go-shellquote 95032a82bc518f77982ea72343cc1ade730072f0 
SRCREV_go-shellquote="95032a82bc518f77982ea72343cc1ade730072f0"
SRC_URI += "git://github.com/kballard/go-shellquote;name=go-shellquote;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/kballard/go-shellquote"

# 	github.com/klauspost/compress v1.15.1
# [1] git ls-remote https://github.com/klauspost/compress 7c7079ec1ed2c07fd15e6f3f369dbae5288051d5 
SRCREV_compress="7c7079ec1ed2c07fd15e6f3f369dbae5288051d5"
SRC_URI += "git://github.com/klauspost/compress;name=compress;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/klauspost/compress"

# 	github.com/mattn/go-colorable v0.1.12
# [1] git ls-remote https://github.com/mattn/go-colorable e1bb79c8d53c38a60962ad4b8f658226cc983710 
SRCREV_go-colorable="e1bb79c8d53c38a60962ad4b8f658226cc983710"
SRC_URI += "git://github.com/mattn/go-colorable;name=go-colorable;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/mattn/go-colorable"

# 	github.com/matttproud/golang_protobuf_extensions v1.0.2-0.20181231171920-c182affec369
# [1] git ls-remote https://github.com/matttproud/golang_protobuf_extensions c182affec369e30f25d3eb8cd8a478dee585ae7d 
SRCREV_golang_protobuf_extensions="c182affec369e30f25d3eb8cd8a478dee585ae7d"
SRC_URI += "git://github.com/matttproud/golang_protobuf_extensions;name=golang_protobuf_extensions;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/matttproud/golang_protobuf_extensions"

# 	github.com/mgutz/ansi v0.0.0-20170206155736-9520e82c474b
# [1] git ls-remote https://github.com/mgutz/ansi 9520e82c474b0a04dd04f8a40959027271bab992 
SRCREV_ansi="9520e82c474b0a04dd04f8a40959027271bab992"
SRC_URI += "git://github.com/mgutz/ansi;name=ansi;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/mgutz/ansi"

# 	github.com/miekg/pkcs11 v1.1.1
# [1] git ls-remote https://github.com/miekg/pkcs11 f3481918a208bd212aa995a41f92d786eb418a7d 
SRCREV_pkcs11="f3481918a208bd212aa995a41f92d786eb418a7d"
SRC_URI += "git://github.com/miekg/pkcs11;name=pkcs11;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/miekg/pkcs11"

# 	github.com/mitchellh/mapstructure v1.5.0
# [1] git ls-remote https://github.com/mitchellh/mapstructure ab69d8d93410fce4361f4912bb1ff88110a81311 
SRCREV_mapstructure="ab69d8d93410fce4361f4912bb1ff88110a81311"
SRC_URI += "git://github.com/mitchellh/mapstructure;name=mapstructure;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/mitchellh/mapstructure"

# 	github.com/moby/locker v1.0.1
# [1] git ls-remote https://github.com/moby/locker 281af2d563954745bea9d1487c965f24d30742fe 
SRCREV_locker="281af2d563954745bea9d1487c965f24d30742fe"
SRC_URI += "git://github.com/moby/locker;name=locker;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/moby/locker"

# 	github.com/moby/sys/signal v0.6.0
# [1] git ls-remote https://github.com/moby/sys d01e595199e1213f509d8ee6e4b03217e6e54517 
SRCREV_signal="d01e595199e1213f509d8ee6e4b03217e6e54517"
SRC_URI += "git://github.com/moby/sys;name=signal;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/moby/sys/signal"

# 	github.com/moby/sys/symlink v0.2.0
# [1] git ls-remote https://github.com/moby/sys 03b9f8d59a07f5206a2264105f4903a222aea964 
SRCREV_symlink="03b9f8d59a07f5206a2264105f4903a222aea964"
SRC_URI += "git://github.com/moby/sys;name=symlink;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/moby/sys/symlink"

# 	github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
# [1] git ls-remote https://github.com/modern-go/concurrent bacd9c7ef1dd9b15be4a9909b8ac7a4e313eec94 
SRCREV_concurrent="bacd9c7ef1dd9b15be4a9909b8ac7a4e313eec94"
SRC_URI += "git://github.com/modern-go/concurrent;name=concurrent;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/modern-go/concurrent"

# 	github.com/modern-go/reflect2 v1.0.2
# [1] git ls-remote https://github.com/modern-go/reflect2 2b33151c9bbc5231aea69b8861c540102b087070 
SRCREV_reflect2="2b33151c9bbc5231aea69b8861c540102b087070"
SRC_URI += "git://github.com/modern-go/reflect2;name=reflect2;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/modern-go/reflect2"

# 	github.com/opencontainers/runc v1.1.2
# [1] git ls-remote https://github.com/opencontainers/runc a916309fff0f838eb94e928713dbc3c0d0ac7aa4 
SRCREV_runc="a916309fff0f838eb94e928713dbc3c0d0ac7aa4"
SRC_URI += "git://github.com/opencontainers/runc;name=runc;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/opencontainers/runc"

# 	github.com/pelletier/go-toml v1.9.4
# [1] git ls-remote https://github.com/pelletier/go-toml b8ba995eaaba4be30c8a8090bdfb4aa61af52054 
SRCREV_go-toml="b8ba995eaaba4be30c8a8090bdfb4aa61af52054"
SRC_URI += "git://github.com/pelletier/go-toml;name=go-toml;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/pelletier/go-toml"

# 	github.com/pmezard/go-difflib v1.0.0
# [1] git ls-remote https://github.com/pmezard/go-difflib 792786c7400a136282c1664665ae0a8db921c6c2 
SRCREV_go-difflib="792786c7400a136282c1664665ae0a8db921c6c2"
SRC_URI += "git://github.com/pmezard/go-difflib;name=go-difflib;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/pmezard/go-difflib"

# 	github.com/prometheus/client_golang v1.12.1
# [1] git ls-remote https://github.com/prometheus/client_golang 2e1c4818ccfdcf953ce399cadad615ff2bed968c 
SRCREV_client_golang="2e1c4818ccfdcf953ce399cadad615ff2bed968c"
SRC_URI += "git://github.com/prometheus/client_golang;name=client_golang;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/prometheus/client_golang"

# 	github.com/prometheus/client_model v0.2.0
# [1] git ls-remote https://github.com/prometheus/client_model 7bc5445566f0fe75b15de23e6b93886e982d7bf9 
SRCREV_client_model="7bc5445566f0fe75b15de23e6b93886e982d7bf9"
SRC_URI += "git://github.com/prometheus/client_model;name=client_model;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/prometheus/client_model"

# 	github.com/prometheus/common v0.32.1
# [1] git ls-remote https://github.com/prometheus/common 2af6d036253eee1a9a08c6ddf6be6d67537bcdff 
SRCREV_common="2af6d036253eee1a9a08c6ddf6be6d67537bcdff"
SRC_URI += "git://github.com/prometheus/common;name=common;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/prometheus/common"

# 	github.com/prometheus/procfs v0.7.3
# [1] git ls-remote https://github.com/prometheus/procfs f436cbb89ece38bf080d446b3ca27053b305eaac 
SRCREV_procfs="f436cbb89ece38bf080d446b3ca27053b305eaac"
SRC_URI += "git://github.com/prometheus/procfs;name=procfs;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/prometheus/procfs"

# 	github.com/qri-io/jsonpointer v0.1.1
# [1] git ls-remote https://github.com/qri-io/jsonpointer d7bf6a8decdffbc01aec9d49b33fc589041b3335 
SRCREV_jsonpointer="d7bf6a8decdffbc01aec9d49b33fc589041b3335"
SRC_URI += "git://github.com/qri-io/jsonpointer;name=jsonpointer;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/qri-io/jsonpointer"

# 	github.com/qri-io/jsonschema v0.2.2-0.20210831022256-780655b2ba0e
# [1] git ls-remote https://github.com/qri-io/jsonschema 780655b2ba0ed03f11ecc8606a8f6e7380bb57be 
SRCREV_jsonschema="780655b2ba0ed03f11ecc8606a8f6e7380bb57be"
SRC_URI += "git://github.com/qri-io/jsonschema;name=jsonschema;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/qri-io/jsonschema"

# 	github.com/tonistiigi/fsutil v0.0.0-20220315205639-9ed612626da3
# [1] git ls-remote https://github.com/tonistiigi/fsutil 9ed612626da3acfc8902f36759d2c4d1ec326132 
SRCREV_fsutil="9ed612626da3acfc8902f36759d2c4d1ec326132"
SRC_URI += "git://github.com/tonistiigi/fsutil;name=fsutil;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/tonistiigi/fsutil"

# 	github.com/tonistiigi/units v0.0.0-20180711220420-6950e57a87ea
# [1] git ls-remote https://github.com/tonistiigi/units 6950e57a87eaf136bbe44ef2ec8e75b9e3569de2 
SRCREV_units="6950e57a87eaf136bbe44ef2ec8e75b9e3569de2"
SRC_URI += "git://github.com/tonistiigi/units;name=units;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/tonistiigi/units"

# 	github.com/tonistiigi/vt100 v0.0.0-20210615222946-8066bb97264f
# [1] git ls-remote https://github.com/tonistiigi/vt100 8066bb97264f56c603341d3fce837bb504e662ef 
SRCREV_vt100="8066bb97264f56c603341d3fce837bb504e662ef"
SRC_URI += "git://github.com/tonistiigi/vt100;name=vt100;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/tonistiigi/vt100"

# 	github.com/xeipuuv/gojsonpointer v0.0.0-20190905194746-02993c407bfb
# [1] git ls-remote https://github.com/xeipuuv/gojsonpointer 02993c407bfbf5f6dae44c4f4b1cf6a39b5fc5bb 
SRCREV_gojsonpointer="02993c407bfbf5f6dae44c4f4b1cf6a39b5fc5bb"
SRC_URI += "git://github.com/xeipuuv/gojsonpointer;name=gojsonpointer;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/xeipuuv/gojsonpointer"

# 	github.com/xeipuuv/gojsonreference v0.0.0-20180127040603-bd5ef7bd5415
# [1] git ls-remote https://github.com/xeipuuv/gojsonreference bd5ef7bd5415a7ac448318e64f11a24cd21e594b 
SRCREV_gojsonreference="bd5ef7bd5415a7ac448318e64f11a24cd21e594b"
SRC_URI += "git://github.com/xeipuuv/gojsonreference;name=gojsonreference;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/xeipuuv/gojsonreference"

# 	github.com/xeipuuv/gojsonschema v1.2.0
# [1] git ls-remote https://github.com/xeipuuv/gojsonschema 82fcdeb203eb6ab2a67d0a623d9c19e5e5a64927 
SRCREV_gojsonschema="82fcdeb203eb6ab2a67d0a623d9c19e5e5a64927"
SRC_URI += "git://github.com/xeipuuv/gojsonschema;name=gojsonschema;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/xeipuuv/gojsonschema"

# 	go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc v0.29.0
# [1] git ls-remote https://github.com/open-telemetry/opentelemetry-go-contrib c17e0db0bb02938fccfa497f72a7c9c5a9ec6e71 
SRCREV_otelgrpc="c17e0db0bb02938fccfa497f72a7c9c5a9ec6e71"
SRC_URI += "git://github.com/open-telemetry/opentelemetry-go-contrib;name=otelgrpc;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/open-telemetry/opentelemetry-go-contrib/instrumentation/google.golang.org/grpc/otelgrpc"

# 	go.opentelemetry.io/otel v1.10.0
# [1] git ls-remote https://github.com/open-telemetry/opentelemetry-go 0e6f9c29c10d6078e8131418e1d1d166c7195d61 
SRCREV_otel="78a1d2d810e0ec42a407f5cc4eb8e9867aad061f"
SRC_URI += "git://github.com/open-telemetry/opentelemetry-go;name=otel;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.opentelemetry.io/otel"

# 	go.opentelemetry.io/otel/exporters/otlp/otlptrace v1.4.1
# [1] git ls-remote https://github.com/open-telemetry/opentelemetry-go 065ba75c4b9750665d8b577b170997cafeb8f903 
SRCREV_otlptrace="065ba75c4b9750665d8b577b170997cafeb8f903"
SRC_URI += "git://github.com/open-telemetry/opentelemetry-go;name=otlptrace;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/open-telemetry/opentelemetry-go/exporters/otlp/otlptrace"

# 	go.opentelemetry.io/otel/internal/metric v0.27.0
# [1] git ls-remote https://github.com/open-telemetry/opentelemetry-go 1bda06288e6df99bdb0705c4ca4870b1f2c82a16 
SRCREV_metric="7c7ba772b9d7784e7c6392f1499f7357ce723b52"
SRC_URI += "git://github.com/open-telemetry/opentelemetry-go;name=metric;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/open-telemetry/opentelemetry-go/internal/metric"

# go.opentelemetry.io/otel/metric v0.27.0
# [1] git ls-remote https://github.com/open-telemetry/opentelemetry-go 1bda06288e6df99bdb0705c4ca4870b1f2c82a16
SRCREV_metric1="5b57299c902bd296de5de2297ebe3096b0a8688b"
SRC_URI += "git://github.com/open-telemetry/opentelemetry-go;name=metric1;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/open-telemetry/opentelemetry-go/metric"

# 	go.opentelemetry.io/otel/sdk v1.4.1
# [1] git ls-remote https://github.com/open-telemetry/opentelemetry-go 065ba75c4b9750665d8b577b170997cafeb8f903 
SRCREV_sdk="065ba75c4b9750665d8b577b170997cafeb8f903"
SRC_URI += "git://github.com/open-telemetry/opentelemetry-go;name=sdk;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/open-telemetry/opentelemetry-go/exporters/otlp/otlptrace"

# 	go.opentelemetry.io/otel/trace v1.10.0
# [1] git ls-remote https://github.com/open-telemetry/opentelemetry-go 0e6f9c29c10d6078e8131418e1d1d166c7195d61 
SRCREV_trace="0e6f9c29c10d6078e8131418e1d1d166c7195d61"
SRC_URI += "git://github.com/open-telemetry/opentelemetry-go;name=trace;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.opentelemetry.io/otel"

# 	go.opentelemetry.io/proto/otlp v0.12.0
# [1] git ls-remote https://github.com/open-telemetry/opentelemetry-proto-go 24bea1abad46b49ccc25cee455e09afca9a19250 
SRCREV_otlp="24bea1abad46b49ccc25cee455e09afca9a19250"
SRC_URI += "git://github.com/open-telemetry/opentelemetry-proto-go;name=otlp;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/open-telemetry/opentelemetry-proto-go/otlp"

# 	golang.org/x/crypto v0.0.0-20220214200702-86341886e292
# [1] git ls-remote https://github.com/golang/crypto 86341886e2925764dc890ad96c141a1bc76043af 
SRCREV_crypto="86341886e2925764dc890ad96c141a1bc76043af"
SRC_URI += "git://github.com/golang/crypto;name=crypto;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/crypto"

# 	golang.org/x/net v0.0.0-20220906165146-f3363e06e74c
# [1] git ls-remote https://github.com/golang/net f3363e06e74cdc304618bf31d898b78590103527 
SRCREV_net="f3363e06e74cdc304618bf31d898b78590103527"
SRC_URI += "git://github.com/golang/net;name=net;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/net"

# 	golang.org/x/oauth2 v0.0.0-20211104180415-d3ed0bb246c8
# [1] git ls-remote https://github.com/golang/oauth2 d3ed0bb246c8d3c75b63937d9a5eecff9c74d7fe 
SRCREV_oauth2="d3ed0bb246c8d3c75b63937d9a5eecff9c74d7fe"
SRC_URI += "git://github.com/golang/oauth2;name=oauth2;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/oauth2"

# 	golang.org/x/sys v0.0.0-20220811171246-fbc7d0a398ab
# [1] git ls-remote https://github.com/golang/sys fbc7d0a398ab184f5d1050e8035f3b19a3b9003f 
SRCREV_sys="fbc7d0a398ab184f5d1050e8035f3b19a3b9003f"
SRC_URI += "git://github.com/golang/sys;name=sys;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/sys"

# 	golang.org/x/term v0.0.0-20210927222741-03fcf44c2211
# [1] git ls-remote https://github.com/golang/term 03fcf44c2211dcd5eb77510b5f7c1fb02d6ded50 
SRCREV_term1="03fcf44c2211dcd5eb77510b5f7c1fb02d6ded50"
SRC_URI += "git://github.com/golang/term;name=term1;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/term"

# 	golang.org/x/text v0.3.7
# [1] git ls-remote https://github.com/golang/text 383b2e75a7a4198c42f8f87833eefb772868a56f 
SRCREV_text="383b2e75a7a4198c42f8f87833eefb772868a56f"
SRC_URI += "git://github.com/golang/text;name=text;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/text"

# 	golang.org/x/time v0.0.0-20220210224613-90d013bbcef8
# [1] git ls-remote https://github.com/golang/time 90d013bbcef8e15b6f78023a0e3b996267153e7d 
SRCREV_time="90d013bbcef8e15b6f78023a0e3b996267153e7d"
SRC_URI += "git://github.com/golang/time;name=time;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/time"

# 	google.golang.org/appengine v1.6.7
# [1] git ls-remote https://github.com/golang/appengine 5d1c1d03f8703c2e81478d9a30e9afa2d3e4bd8a 
SRCREV_appengine="5d1c1d03f8703c2e81478d9a30e9afa2d3e4bd8a"
SRC_URI += "git://github.com/golang/appengine;name=appengine;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/golang/appengine"

# 	google.golang.org/genproto v0.0.0-20220314164441-57ef72a4c106
# [1] git ls-remote https://github.com/googleapis/go-genproto 57ef72a4c106086f9e50d41d88cdb1dbbce5486e 
SRCREV_genproto="57ef72a4c106086f9e50d41d88cdb1dbbce5486e"
SRC_URI += "git://github.com/googleapis/go-genproto;name=genproto;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/googleapis/go-genproto"

# 	google.golang.org/grpc v1.45.0
# [1] git ls-remote https://github.com/grpc/grpc-go a82cc96f07c960e02623688e4067ae6b7895334a 
SRCREV_grpc="a82cc96f07c960e02623688e4067ae6b7895334a"
SRC_URI += "git://github.com/grpc/grpc-go;name=grpc;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/grpc/grpc-go"

# 	google.golang.org/protobuf v1.27.1
# [1] git ls-remote https://github.com/protocolbuffers/protobuf-go b92717ecb630d4a4824b372bf98c729d87311a4d 
SRCREV_protobuf12="b92717ecb630d4a4824b372bf98c729d87311a4d"
SRC_URI += "git://github.com/protocolbuffers/protobuf-go;name=protobuf12;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/protocolbuffers/protobuf-go"

# 	gopkg.in/inf.v0 v0.9.1
# [1] git ls-remote https://gopkg.in/inf.v0 d2d2541c53f18d2a059457998ce2876cc8e67cbf 
SRCREV_inf.v0="d2d2541c53f18d2a059457998ce2876cc8e67cbf"
SRC_URI += "git://gopkg.in/inf.v0;name=inf.v0;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/gopkg.in/inf.v0"

# 	gopkg.in/yaml.v3 v3.0.1
# [1] git ls-remote https://gopkg.in/yaml.v3 f6f7691b1fdeb513f56608cd2c32c51f8194bf51 
SRCREV_yaml.v3="f6f7691b1fdeb513f56608cd2c32c51f8194bf51"
SRC_URI += "git://gopkg.in/yaml.v3;name=yaml.v3;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/gopkg.in/yaml.v3"

# 	k8s.io/klog/v2 v2.60.1
# [1] git ls-remote https://github.com/kubernetes/klog b46e95d6825a8558b8ca00afc4fbc26acfb5605a 
SRCREV_v212="b46e95d6825a8558b8ca00afc4fbc26acfb5605a"
SRC_URI += "git://github.com/kubernetes/klog;name=v212;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/k8s.io/klog/v2"

# 	k8s.io/utils v0.0.0-20220210201930-3a6ce19ff2f9
# [1] git ls-remote https://github.com/kubernetes/utils 3a6ce19ff2f91f3dc49243f90f7834a0f1e4aaf3 
SRCREV_utils="3a6ce19ff2f91f3dc49243f90f7834a0f1e4aaf3"
SRC_URI += "git://github.com/kubernetes/utils;name=utils;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/k8s.io/utils"

# 	sigs.k8s.io/structured-merge-diff/v4 v4.2.1
# [1] git ls-remote https://github.com/kubernetes-sigs/structured-merge-diff 65611e5f7fc60e909529889c29faa9cac17cb485 
SRCREV_v4="65611e5f7fc60e909529889c29faa9cac17cb485"
SRC_URI += "git://github.com/kubernetes-sigs/structured-merge-diff;name=v4;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/sigs.k8s.io/structured-merge-diff/v4"

# 	sigs.k8s.io/yaml v1.2.0
# [1] git ls-remote https://github.com/kubernetes-sigs/yaml 9fc95527decd95bb9d28cc2eab08179b2d0f6971 
SRCREV_yaml="9fc95527decd95bb9d28cc2eab08179b2d0f6971"
SRC_URI += "git://github.com/kubernetes-sigs/yaml;name=yaml;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/sigs.k8s.io/yaml"

# 	github.com/cenkalti/backoff/v4 v4.1.2
# [1] git ls-remote https://github.com/cenkalti/backoff a78d3804c2c84f0a3178648138442c9b07665bda 
SRCREV_v41="a78d3804c2c84f0a3178648138442c9b07665bda"
SRC_URI += "git://github.com/cenkalti/backoff;name=v41;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/cenkalti/backoff/v4"

# 	github.com/cyberphone/json-canonicalization v0.0.0-20210303052042-6bc126869bf4
# [1] git ls-remote https://github.com/cyberphone/json-canonicalization 6bc126869bf4f04aeb0e2b98346a376c976691fa 
SRCREV_json-canonicalization="6bc126869bf4f04aeb0e2b98346a376c976691fa"
SRC_URI += "git://github.com/cyberphone/json-canonicalization;name=json-canonicalization;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/cyberphone/json-canonicalization"

# 	github.com/googleapis/gnostic v0.5.5
# [1] git ls-remote https://github.com/googleapis/gnostic 1550ae29653d42db69c8a98d368648be7f2c488d 
SRCREV_gnostic="1550ae29653d42db69c8a98d368648be7f2c488d"
SRC_URI += "git://github.com/googleapis/gnostic;name=gnostic;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/googleapis/gnostic"

# 	github.com/moby/spdystream v0.2.0
# [1] git ls-remote https://github.com/moby/spdystream dbc715126c0e3fa07721879c6d265b2b82c71e5b 
SRCREV_spdystream="dbc715126c0e3fa07721879c6d265b2b82c71e5b"
SRC_URI += "git://github.com/moby/spdystream;name=spdystream;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/moby/spdystream"

# 	github.com/serialx/hashring v0.0.0-20190422032157-8b2912629002
# [1] git ls-remote https://github.com/serialx/hashring 8b2912629002c928de72c69aae20c8600bef41a6 
SRCREV_hashring="8b2912629002c928de72c69aae20c8600bef41a6"
SRC_URI += "git://github.com/serialx/hashring;name=hashring;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/serialx/hashring"

# 	github.com/zmap/zcrypto v0.0.0-20220605182715-4dfcec6e9a8c
# [1] git ls-remote https://github.com/zmap/zcrypto 4dfcec6e9a8c2014f73dd584e64dc797129d77b8 
SRCREV_zcrypto="4dfcec6e9a8c2014f73dd584e64dc797129d77b8"
SRC_URI += "git://github.com/zmap/zcrypto;name=zcrypto;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/zmap/zcrypto"

# 	github.com/zmap/zlint v1.1.0
# [1] git ls-remote https://github.com/zmap/zlint 71201e7f6c374a07357066504a13577aed052cf6 
SRCREV_zlint="71201e7f6c374a07357066504a13577aed052cf6"
SRC_URI += "git://github.com/zmap/zlint;name=zlint;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/zmap/zlint"

# 	go.opentelemetry.io/otel/exporters/otlp/internal/retry v1.4.1
# [1] git ls-remote https://github.com/open-telemetry/opentelemetry-go 065ba75c4b9750665d8b577b170997cafeb8f903 
SRCREV_retry="065ba75c4b9750665d8b577b170997cafeb8f903"
SRC_URI += "git://github.com/open-telemetry/opentelemetry-go;name=retry;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/open-telemetry/opentelemetry-go/exporters/otlp/otlptrace"

# github.com/docker/cli v20.10.3-0.20220309205733-2b52f62e9627+incompatible
# [1] git ls-remote https://github.com/docker/cli 2b52f62e962783ef39b53d1cb95e1d435b33f3cd 
SRCREV_cli1="2b52f62e962783ef39b53d1cb95e1d435b33f3cd"
SRC_URI += "git://github.com/docker/cli;name=cli1;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/docker/cli"

# github.com/docker/docker v20.10.3-0.20220309172631-83b51522df43+incompatible
# [1] git ls-remote https://github.com/docker/docker 83b51522df43866e39f7c757a6ab84ef4050eeb3 
SRCREV_docker1="83b51522df43866e39f7c757a6ab84ef4050eeb3"
SRC_URI += "git://github.com/docker/docker;name=docker1;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/docker/docker83b51522df43866e39f7c757a6ab84ef4050eeb3"

# k8s.io/api v0.22.4
# [1] git ls-remote https://github.com/kubernetes/api 7b9552ec29b4eb9d6e647f705bae66e800311011 
SRCREV_api1="7b9552ec29b4eb9d6e647f705bae66e800311011"
SRC_URI += "git://github.com/kubernetes/api;name=api1;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/k8s.io/api"

# k8s.io/apimachinery v0.22.4
# [1] git ls-remote https://github.com/kubernetes/apimachinery e757da007984b92fc3d1da457f4bc3b900606642 
SRCREV_apimachinery="e757da007984b92fc3d1da457f4bc3b900606642"
SRC_URI += "git://github.com/kubernetes/apimachinery;name=apimachinery;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/k8s.io/apimachinery"

# k8s.io/client-go v0.22.4
# [1] git ls-remote https://github.com/kubernetes/client-go 29f81448d77a50b041e21e44cbf0269450e8ae03 
SRCREV_client-go="29f81448d77a50b041e21e44cbf0269450e8ae03"
SRC_URI += "git://github.com/kubernetes/client-go;name=client-go;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/k8s.io/client-go"

SRCREV_buildx="6224def4dd2c3d347eee19db595348c50d7cb491"
SRC_URI += "git://github.com/docker/buildx;name=buildx;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/docker/buildx"

# github.com/moby/sys/mount v0.3.0
# [1] git ls-remote https://github.com/moby/sys a03c53e37993851f541c803edc422854ac9a8ef9
SRCREV_mount="a03c53e37993851f541c803edc422854ac9a8ef9"
SRC_URI += "git://github.com/moby/sys;name=mount;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/moby/sys/mount"

# github.com/moby/sys/mountinfo v0.6.0
# [1] git ls-remote https://github.com/moby/sys d01e595199e1213f509d8ee6e4b03217e6e54517
SRCREV_mountinfo="d01e595199e1213f509d8ee6e4b03217e6e54517"
SRC_URI += "git://github.com/moby/sys;name=mountinfo;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/moby/sys/mountinfo"

# github.com/moby/sys/symlink v0.2.0
# [1] git ls-remote https://github.com/moby/sys 03b9f8d59a07f5206a2264105f4903a222aea964
SRCREV_symlink="03b9f8d59a07f5206a2264105f4903a222aea964"
SRC_URI += "git://github.com/moby/sys;name=symlink;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/moby/sys/symlink"

