#!/usr/bin/bash
#
# Copyright (c) MicroHobby <matheus@castello.eng.br> 2023
# All rights reserved.
# 

# check if we have an internet connection
# retry 3x
for i in {1..3}
do
    if ping -c 1 google.com
    then
        break
    # else we are in the last iteration exit
    elif [ $i -eq 3 ]
    then
        echo "E: No internet connection"
        # exit with success to avoid taint the systemd status
        exit 0
    fi

    sleep 3
done

export JSON_OUTPUT=1

# create the info in json format
tdx-info > /tmp/tdx-info.json

# get the data
BOARDMODEL=$(cat /tmp/tdx-info.json | jq '."hardware-info"."hw-model"')
BOARDARCH=$(cat /tmp/tdx-info.json | jq '."hardware-info"."processor-arch"')
OSRELEASE=$(cat /tmp/tdx-info.json | jq '."software-summary"."distro-version"')
DATETIME=$(date +%Y-%m-%d)

# get emerg, alert, crit, err, warning dmesg levels
DMESG=$(dmesg -r --level=emerg,alert,crit,err,warn)

# query the region
REGION=$(curl -s https://ipapi.co/city)

# debug
echo "REGION: $REGION"
echo "BOARDMODEL: $BOARDMODEL"
echo "BOARDARCH: $BOARDARCH"
echo "OSRELEASE: $OSRELEASE"
echo "DATETIME: $DATETIME"
echo "DMESG: $DMESG"

# do it
curl --request POST \
  --url http://castello.dev.br/api/telemetry/add \
  --data-urlencode "region=$REGION" \
  --data-urlencode "dateTime=$DATETIME" \
  --data-urlencode "boardarch=$BOARDARCH" \
  --data-urlencode "boardmodel=$BOARDMODEL" \
  --data-urlencode "osrelease=$OSRELEASE" \
  --data-urlencode "dmesg=\"$DMESG\""

exit 0
