#!/bin/bash
# -*- mode: shell-script-mode; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 4 -*-
#
# Copyright (C) 2012-13 O.S. Systems Software LTDA.
# Copyright (C) 2017 Open Source Foundries Ltd.
# Authored-by:  Otavio Salvador <otavio@ossystems.com.br>
# Adopted to Angstrom:  Khem Raj <raj.khem@gmail.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

env_cleanup() {
    unset MACHLAYERS DISTLAYERS DISTRO_DEFAULT OEROOT
    unset ITEM MANIFESTS REPLY EULA_ACCEPTED READ_EULA
    unset usage oldmach
    unset MANIFEST_FILE INTEGRATION_BUILD
}

usage () {
    cat >&2 <<EOF

Usage: [DISTRO=<DISTRO>] [MACHINE=<MACHINE>] [EULA=1] source ${BASH_SOURCE[0]} [BUILDDIR]

If no DISTRO is set, 'torizon|torizon-upstream' will be chosen depending on MACHINE.
If no MACHINE is set, list all possible machines, and ask user to choose.
If no EULA is set, user will be asked to read it and to accept it.
If no BUILDIR is set, it will be set to build-\$DISTRO.

EOF
}

variable_validation() {
    local LAYERS=$1
    local -n VARREF=$2
    local VARNAME=$(echo $2 | tr '[:upper:]' '[:lower:]')

    if [ -z "${VARREF}" -o "${VARREF}" = "INVALID" ]; then
        local VARTABLE=
        for ITEM in ${LAYERS}; do
            VARTABLE="${VARTABLE} $(echo "${ITEM}" | cut -d'(' -f1) \
                      $(echo "${ITEM}" | cut -d'(' -f2 | cut -d')' -f1)"
        done

        # whiptail
        which whiptail > /dev/null 2>&1
        if [ $? -eq 0 ]; then
            VARREF=$(whiptail --title "Available ${VARNAME}s" --menu \
                     "Please choose a ${VARNAME}" 0 0 20 \
                     ${VARTABLE} 3>&1 1>&2 2>&3)
        fi

        # dialog
        if [ -z "${VARREF}" -o "${VARREF}" = "INVALID" ]; then
            which dialog > /dev/null 2>&1
            if [ $? -eq 0 ]; then
                VARREF=$(dialog --title "Available ${VARNAME}s" --menu \
                        "Please choose a ${VARNAME}" 0 0 20 ${VARTABLE} \
                        3>&1 1>&2 2>&3)
            fi
        fi

        # guard against Ctrl-D or cancel
        if [  -z "${VARREF}" -o "${VARREF}" = "INVALID" ]; then
            echo "To choose a ${VARNAME} interactively please install whiptail or dialog."
            echo "To choose a ${VARNAME} non-interactively please use the following:"
            echo "    ${!VARREF}=<your-${VARNAME}> . ./setup-environment"
            echo ""
            echo "Press <ENTER> to see a list of your choices"
            read -r
            echo "${LAYERS}" | sed -e 's/(/ (/g' | sed -e 's/)/)\n/g' |
                    sed -e 's/^ */\t/g'
            return 1
        fi
    fi

    return 0
}

trap env_cleanup RETURN

if [ "$(whoami)" = "root" ]; then
    echo "ERROR: do not build TorizonCore as root. Exiting..." >&2
    return 1
fi

if [ $# -gt 1 ]; then
    usage
    return 1
fi

OEROOT=$(pwd)
cd "$OEROOT"
if [ -n "$ZSH_VERSION" ]; then
    setopt sh_word_split
    setopt clobber
elif [ -n "$BASH_VERSION" ]; then
    set +o noclobber
fi

#
# Create a common list of "<machine>(<layer>)", sorted by <machine>
# Blacklist unsupported machines of TorizonCore
MACHLAYERS=$(find layers/ -print | grep "conf/machine/.*\.conf" |
            grep -E '(apalis.*\.conf|colibri.*\.conf|verdin.*\.conf|qemuarm64\.conf|genericx86-64\.conf|raspberrypi4-64\.conf|raspberrypi3-64\.conf|raspberrypi0-2w-64\.conf|raspberrypi0-wifi\.conf|intel-corei7-64\.conf|nezha-allwinner-d1\.conf|beaglebone-yocto\.conf|beagleplay\.conf)' |
            grep -E -v '(imx7-nand|colibri-vf|tk1|colibri-imx7|colibri-imx6ull|verdin-am62-k3r5)\.conf' |
            sed -e 's/\.conf//g' -e 's/layers\///' |
            awk -F'/conf/machine/' '{print $NF "(" $1 ")"}' | LC_ALL=C sort)

# MACHINE sanity check
echo $MACHLAYERS | grep -q "$MACHINE(.*)" || MACHINE="INVALID"

# Validate MACHINE
variable_validation "$MACHLAYERS" "MACHINE" || return 1

# DISTRO defaults to 'torizon' for am62/imx8/qemuarm64/genericx86-64 machines
# DISTRO defaults to 'torizon-upstream' for other machines
DISTRO_DEFAULT="torizon-upstream" && echo "$MACHINE" | grep -E -q '(imx8|am62|qemuarm64|genericx86-64)' && DISTRO_DEFAULT="torizon"
DISTRO=${DISTRO:-$DISTRO_DEFAULT}

# Create a common list of "<distro>(<layer>)" supported by TorizonCore, sorted by <distro>
DISTLAYERS=$(find layers/meta-common-torizon -print | grep "conf/distro/.*\.conf" |
            sed -e 's/\.conf//g' -e 's/layers\///' |
            awk -F'/conf/distro/' '{print $NF "(" $1 ")"}' | LC_ALL=C sort)

# DISTRO sanity check
echo $DISTLAYERS | grep -q "$DISTRO(.*)" || DISTRO="INVALID"

# Validate DISTRO
variable_validation "$DISTLAYERS" "DISTRO" || return 1

if [ -z "${SDKMACHINE}" ]; then
    SDKMACHINE='x86_64'
fi

MANIFESTS="${OEROOT}"/.repo/manifests
SCRIPTS="${OEROOT}"/layers/meta-common-torizon/scripts

# We can be called with only 1 parameter max (build folder)
BUILDDIR=${1:-build-$DISTRO}
# If current BUILDDIR is relative then prepend OEROOT
case ${BUILDDIR} in
    /* ) ;;
    *  ) BUILDDIR=$(readlink -f ${BUILDDIR});;
esac
# Get rid of double slash. sed calls in OE staging_processfixme
# seems to have troubles if this makes it into OE variables.
BUILDDIR=${BUILDDIR%%/}

# Set BBPATH for recipetool
BBPATH=${BUILDDIR}

# Clean up PATH, because if it includes tokens to current directories somehow,
# wrong binaries can be used instead of the expected ones during task execution
PATH=$(echo "${PATH}" | sed 's/\(:.\|:\)*:/:/g;s/^.\?://;s/:.\?$//')
PATH="${OEROOT}/bitbake/bin:${OEROOT}/.repo/repo:${PATH}"
PATH="${OEROOT}/layers/openembedded-core/bitbake/bin:${PATH}"
PATH="${OEROOT}/layers/openembedded-core/scripts:${PATH}"
# Remove duplicate path entries
PATH=$(echo "$PATH" |
       awk -F: '{for (i=1;i<=NF;i++) { if ( !x[$i]++ ) printf("%s:",$i); }}' |
       sed 's/:$//')

BB_ENV_PASSTHROUGH_ADDITIONS_OE="MACHINE DISTRO TCMODE TCLIBC HTTP_PROXY http_proxy \
HTTPS_PROXY https_proxy FTP_PROXY ftp_proxy FTPS_PROXY ftps_proxy ALL_PROXY \
all_proxy NO_PROXY no_proxy SSH_AGENT_PID SSH_AUTH_SOCK BB_SRCREV_POLICY \
SDKMACHINE BB_NUMBER_THREADS BB_NO_NETWORK PARALLEL_MAKE GIT_PROXY_COMMAND \
SOCKS5_PASSWD SOCKS5_USER SCREENDIR STAMPS_DIR BBPATH_EXTRA BB_SETSCENE_ENFORCE"

BB_ENV_PASSTHROUGH_ADDITIONS="$(echo $BB_ENV_PASSTHROUGH_ADDITIONS $BB_ENV_PASSTHROUGH_ADDITIONS_OE | tr ' ' '\n' | LC_ALL=C sort --unique | tr '\n' ' ')"

export PATH
export BUILDDIR
export BBPATH
export BB_ENV_PASSTHROUGH_ADDITIONS

AUTO_CONF_CREATED=0
mkdir -p "${BUILDDIR}"/conf && cd "${BUILDDIR}"
if [ -f "conf/auto.conf" ]; then
    oldmach=$(egrep "^MACHINE \?=" "conf/auto.conf" |
             sed -e 's%^MACHINE ?= %%' | sed -e 's/^"//' -e 's/"$//')
    olddisto=$(egrep "^DISTRO \?=" "conf/auto.conf" |
             sed -e 's%^DISTRO ?= %%' | sed -e 's/^"//' -e 's/"$//')
    eulaacpt=$(egrep '^\s*ACCEPT_FSL_EULA\s*=\s*\".*\"' conf/local.conf |
             sed -e 's%^\s*ACCEPT_FSL_EULA\s*=\s*%%' | sed -e 's/^"//' -e 's/"$//')
    AUTO_CONF_CREATED=1
fi

if [ -e conf/checksum -a "${MACHINE}" = "$oldmach" -a "${DISTRO}" = "$olddisto" -a "${EULA}" = "$eulaacpt" ]; then
    if sha512sum --quiet -c conf/checksum >/dev/null 2>&1; then
        return 0
    fi
fi

# Evaluate new checksum and regenerate the conf files
sha512sum "${SCRIPTS}"/setup-environment-internal 2>&1 > conf/checksum

if [ ! -f "conf/local.conf" ]; then
    cp "${SCRIPTS}"/../conf/template/local.conf conf/local.conf
fi
ln -sf "${SCRIPTS}"/../conf/template/bblayers.conf conf/bblayers.conf
ln -sf "${MANIFESTS}"/README.md README.md
ln -sf "${MANIFESTS}" "${OEROOT}"/layers/

MANIFEST_FILE="${MANIFESTS}"/../manifest.xml
INTEGRATION_BUILD=0

if [ -L "$MANIFEST_FILE" ]; then
    if [ "$(basename `readlink -f "$MANIFEST_FILE"`)" != "default.xml" ]; then
        INTEGRATION_BUILD=1
    fi
else
    if ! cat $MANIFEST_FILE | grep -q "torizoncore/default.xml"; then
        INTEGRATION_BUILD=1
    fi
fi

if [ "$INTEGRATION_BUILD" = "1" ] && [ "$AUTO_CONF_CREATED" = "0" ]; then
    cat > conf/auto.conf <<EOF
# This is needed when building on integration. With use-head-next you
# always get the newest software (u-boot, kernel, aktualizr-torizon, etc).
# Building on integration without use-head-next your build may fail.
DISTROOVERRIDES .= ":use-head-next"

EOF
fi

if [ "$AUTO_CONF_CREATED" = "0" ]; then
    cat >> conf/auto.conf <<EOF
DISTRO ?= "${DISTRO}"
MACHINE ?= "${MACHINE}"
SDKMACHINE ?= "${SDKMACHINE}"

# Extra options that can be changed by the user
INHERIT += "rm_work"
EOF
else
    sed -i "s/^DISTRO ?= \"[^\"]*\"$/DISTRO ?= \"${DISTRO}\"/" conf/auto.conf
    sed -i "s/^MACHINE ?= \"[^\"]*\"$/MACHINE ?= \"${MACHINE}\"/" conf/auto.conf
    sed -i "s/^SDKMACHINE ?= \"[^\"]*\"$/SDKMACHINE ?= \"${SDKMACHINE}\"/" conf/auto.conf
fi

cat > conf/site.conf <<_EOF
SCONF_VERSION = "1"

# Where to store sources
DL_DIR ?= "${OEROOT}/downloads"

# Where to save shared state
SSTATE_DIR ?= "${OEROOT}/sstate-cache"

# Where to save the build system work output
TMPDIR = "${BUILDDIR}/tmp"

# Where to save the packages and images
DEPLOY_DIR = "${BUILDDIR}/deploy"

# Go through the Firewall
#HTTP_PROXY = "http://${PROXYHOST}:${PROXYPORT}/"
_EOF

EULA_ACCEPTED=""

if egrep -q '^\s*ACCEPT_FSL_EULA\s*=\s*\"[^\"]*\"' conf/local.conf; then
    EULA_ACCEPTED=1
fi

if [ -z "$EULA_ACCEPTED" ] && [ -n "$EULA" ]; then
    # Freescale's EULA is not accepted int conf/local.conf but
    # user set the EULA environment variable, so we set
    # ACCEPT_FSL_EULA with $EULA value
    cat >> conf/local.conf <<EOF

# BSP depends on NXP packages and firmware which are covered by an
# End User License Agreement (EULA). To have the right to use these
# binaries in the image, ACCEPT_FSL_EULA must be set to '1'
ACCEPT_FSL_EULA = "$EULA"
EOF
elif [ -n "$EULA_ACCEPTED" ]; then
    # Freescale's EULA has been accepted before and it is set in conf/local.conf.
    if [ -n "$EULA" ]; then
        # If EULA is not null, we change it to the value passed by it
        sed -i "s/^\s*ACCEPT_FSL_EULA\s*=\s*\"[^\"]*\"$/ACCEPT_FSL_EULA = \"${EULA}\"/" conf/local.conf
    fi
else
    # Freescale's EULA has not been accepted and EULA environment
    # variable is not set. Show user the EULA and ask they accept
    cat <<EOF

The BSP for $MACHINE depends on packages and firmware which are covered by an
End User License Agreement (EULA). To have the right to use these binaries
in your images, you need to read and accept the following...

EOF

    echo
    REPLY=
    while [ -z "$REPLY" ]; do
        echo -n "Would you like to read the EULA ? (y/n) "
        read -r REPLY
        case "$REPLY" in
            y|Y)
                READ_EULA=1
                ;;
            n|N)
                READ_EULA=0
                ;;
            *)
                REPLY=
                ;;
        esac
    done

    if [ "$READ_EULA" = 1 ]; then
        more -d "${OEROOT}/layers/meta-freescale/EULA"
        echo
        REPLY=
        while [ -z "$REPLY" ]; do
            echo -n "Do you accept the EULA you just read? (y/n) "
            read -r REPLY
            case "$REPLY" in
                y|Y)
                    echo "EULA has been accepted."
                    cat >> conf/local.conf <<EOF

# BSP depends on NXP packages and firmware which are covered by an
# End User License Agreement (EULA). To have the right to use these
# binaries in the image, ACCEPT_FSL_EULA must be set to '1'
ACCEPT_FSL_EULA = "1"
EOF
                    ;;
                n|N)
                    echo "EULA has not been accepted."
                    ;;
                *)
                    REPLY=
                    ;;
            esac
        done
    fi
fi

# cat <<EOF

# Welcome to Toradex TorizonCore

# For more information about OpenEmbedded see their website:

#     http://www.openembedded.org/

# Your build environemnt has been configured with:

#     MACHINE = ${MACHINE}
#     SDKMACHINE = ${SDKMACHINE}
#     DISTRO = ${DISTRO}

# You can now run 'bitbake <target>'

# Some of common targets are:

#     torizon-core-docker
#     torizon-core-podman
#     torizon-core-lite

# EOF

if [ "${MACHINE}" = "qemuarm64" ]; then
    cat <<EOF
You can also run generated qemuarm64 image with runqemu by:

    runqemu qemuarm64
    xtightvncviewer 127.0.0.1

EOF
fi

if [ "${MACHINE}" = "genericx86-64" ]; then
    cat <<EOF
You can also run generated genericx86-64 image in VirtualBox by:

    Create a new machine by choosing 'Other Linux (64-bits)' type
    Choose an existing virtual hard disk file: deploy/images/genericx86-64/torizon-core-docker-genericx86-64.wic.vmdk
    Enable EFI boot mode through: Settings -> System -> Extended Features -> Enable EFI
    Start the machine

EOF
fi
